attributes:
    homebrewalt:
        apps:
            - docker
            - fig
            - git
            - go
            - hub
            - tree
        cask_apps:
            - firefox
            - gitx-rowanj
            - google-chrome
            - iterm2
            - sequel-pro
            - vagrant

